// automatically generated by the FlatBuffers compiler, do not modify

export { Items, ItemsT } from './bimrepo/items.js';
export { PropertyType } from './bimrepo/property-type.js';
export { Schema, SchemaT } from './bimrepo/schema.js';
export { property, propertyT } from './bimrepo/property.js';
export { shape, shapeT } from './bimrepo/shape.js';
