// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ComponentData, ComponentDataT } from '../bimrepo/component-data.js';
import { ComponentIdentifier, ComponentIdentifierT } from '../bimrepo/component-identifier.js';


export class Component implements flatbuffers.IUnpackableObject<ComponentT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Component {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsComponent(bb:flatbuffers.ByteBuffer, obj?:Component):Component {
  return (obj || new Component()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsComponent(bb:flatbuffers.ByteBuffer, obj?:Component):Component {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Component()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id(obj?:ComponentIdentifier):ComponentIdentifier|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ComponentIdentifier()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

data(index: number, obj?:ComponentData):ComponentData|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ComponentData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

dataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startComponent(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dataOffset, 0);
}

static createDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endComponent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishComponentBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedComponentBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createComponent(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  Component.startComponent(builder);
  Component.addId(builder, idOffset);
  Component.addData(builder, dataOffset);
  return Component.endComponent(builder);
}

unpack(): ComponentT {
  return new ComponentT(
    (this.id() !== null ? this.id()!.unpack() : null),
    this.bb!.createObjList<ComponentData, ComponentDataT>(this.data.bind(this), this.dataLength())
  );
}


unpackTo(_o: ComponentT): void {
  _o.id = (this.id() !== null ? this.id()!.unpack() : null);
  _o.data = this.bb!.createObjList<ComponentData, ComponentDataT>(this.data.bind(this), this.dataLength());
}
}

export class ComponentT implements flatbuffers.IGeneratedObject {
constructor(
  public id: ComponentIdentifierT|null = null,
  public data: (ComponentDataT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? this.id!.pack(builder) : 0);
  const data = Component.createDataVector(builder, builder.createObjectOffsetList(this.data));

  return Component.createComponent(builder,
    id,
    data
  );
}
}
