// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bimrepo
{

public enum ComponentDataType : sbyte
{
  Number = 1,
  String = 2,
  Boolean = 3,
  ArrayStart = 4,
  ArrayEnd = 5,
};


}
