// automatically generated by the FlatBuffers compiler, do not modify

export enum ComponentDataType {
  Number = 1,
  String = 2,
  Boolean = 3,
  ArrayStart = 4,
  ArrayEnd = 5,
  Ref = 6,
  Empty = 7
}
