// automatically generated by the FlatBuffers compiler, do not modify

export enum ComponentDataType {
  Int8 = 1,
  Int16 = 2,
  Int32 = 3,
  Int64 = 4,
  Uint8 = 5,
  Uint16 = 6,
  Uint32 = 7,
  Uint64 = 8,
  Float32 = 9,
  Float64 = 10,
  Blob = 11,
  String = 12,
  Boolean = 13,
  ArrayStart = 14,
  ArrayEnd = 15,
  Ref = 16,
  Empty = 17
}
