// automatically generated by the FlatBuffers compiler, do not modify

export enum PropertyType {
  Int8 = 1,
  Int16 = 2,
  Int32 = 3,
  Int64 = 4,
  Uint8 = 5,
  Uint16 = 6,
  Uint32 = 7,
  Uint64 = 8,
  Float32 = 9,
  Float64 = 10,
  Blob = 11,
  Array = 12,
  String = 13,
  Boolean = 14,
  Ref = 15
}
