// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace bimrepo
{

public enum PropertyType : sbyte
{
  Number = 1,
  Array = 2,
  String = 3,
  Boolean = 4,
  Ref = 5,
};


}
